### ISSUE TITLE
podcast :)

### ISSUE THREAD

**Issue by arnellebalane** [uncaughtxcptn/todo#2]
How are we going to do this?

**Comment by arnellebalane** [comment]
@aldnav @name3anad @kiellabian @jedijulia @jayzces

**Comment by jayzces** [comment]
Decide on a topic. Existing podcasts for reference: https://itunes.apple.com/ug/genre/podcasts-technology/id1318?mt=2

**Comment by arnellebalane** [comment]
Technology and Computers? Plus a little bit of Gaming, maybe?

**Comment by arnellebalane** [comment]
Probably not gonna do this one in the foreseeable future, so closing for now.
